### PR TITLE
Update bundled python sources

### PR DESCRIPTION
**Pull request by subpop**
- Update grpcio: 1.48.2 -> 1.65.1
- Update grpcio_tools: 1.48.2 -> 1.65.1
- Update protobuf: 3.19.6 -> 5.27.2
- Drop EL9 from packit; the new versions of the above pacakges require
  Python versions only available on EL10 and newer.

### CODE REVIEW

**Comment by ptoscano** [comment]
hmmm
```
      Looking in links: ./vendor
      Ignoring Cython: markers 'python_version >= "3.13"' don't match your environment
```

**Comment by subpop** [comment]
> hmmm
> 
> ```
>       Looking in links: ./vendor
>       Ignoring Cython: markers 'python_version >= "3.13"' don't match your environment
> ```

Yea. I don't have Python 3.13 on my local hosts, so I don't know why (yet) that error is showing up, or if that is even the cause of the problem.

**Comment by subpop** [comment]
Obsoleted by #36

**Pull request closed without merging**
