### PR TITLE
Add initial tmt test plan

### PR DESCRIPTION
**Pull request by subpop**
Initialize a basic test plan with tmt and add a simple smoke test to run the worker.

### CODE REVIEW

**Comment by subpop** [comment]
Waiting for https://github.com/packit/deployment/pull/577 to build in the RHEL testing farm.

**Comment by Lorquas** [comment]
I added the testing farm key just now.  PR in general looks good to me as a starting point; do we want to add a fedora-all test target?

**Comment by subpop** [comment]
I didn't add Fedora here, because this version of rhc-worker-playbook cannot run on current versions of Fedora. I have another PR (#26) that expands the distributions to include Fedora and EL10, and drop EL8.

**Pull request merged**
